version: '3'
volumes:
  docker_data:

services:
  postgres:
    # networks:
    #   - network1
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_DB: w3com
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - docker_data:/var/lib/postgresql/data
      # - ./docker_data:/var/lib/postgresql/data

